language: python

os:
  - linux
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov-report term --cov=pycartool/tests/

env:

after_success:
  - codecov
